refactor: 소셜로그인 과정 개편, test코드 추가/수정, docs추가
AmorGakCo/Backend pull request #41
Opened 2024-08-26 15:15 UTC by songhaechan

## #️⃣연관된 이슈

> ex) #40 

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요.(이미지 첨부 가능)

## 💬리뷰 요구사항

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요.

2024-08-26 15:50 UTC, ohksj77 requested changes
수정 작업을 고민을 많이 하며 하신듯 보입니다.
고생하셨습니다.

2024-08-26 15:50 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/group/service/S2GroupLocationService.java
> +        System.out.println("cellTokens = " + cellTokens);
출력문은 제거하는게 좋을 것 같습니다.

2024-08-26 15:50 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/member/domain/Member.java
> +        return this;
update 함수에 반환하는 책임이 필요할까요? update 함수는 갱신의 책임만 갖는건 어떤가요?
update 함수가 어떤 값을 반환할지 한 번에 알기 어렵다는 문제도 있습니다.
그리고, 사용하는 측에 이미 인스턴스가 존재하지 않을까요?

2024-08-26 15:50 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/member/service/MemberService.java
> +    }
Optional.ifPresentOrElse() 를 사용하면 update 메서드가 값을 반환하지 않아도 될 것 같습니다.

2024-08-26 15:50 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/oauth2/provider/kakao/KakaoAuthorization.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
이 설정은 application.yml 에서 전역으로 설정하는 방법도 있을 것 같습니다.

2024-08-26 15:50 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/oauth2/provider/Oauth2ProviderComposite.java
> +    }
EnumMap 사용은 고려해보셨나요?

2024-08-26 15:50 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/oauth2/provider/Oauth2ProviderService.java
> +}
단순히 Map에 넣기 위한 값을 꺼내오려고 만든 메서드는 큰 의미가 없어보입니다. 딱히 어떠한 행동을 하기 보다는 값만 넘겨주는 것 같네요.
차라리 Enum.values() 를 사용하여 Map을 채우는건 어떤가요?

2024-08-26 15:50 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/oauth2/provider/Oauth2ProviderComposite.java
> +}
단순히 인스턴스들을 저장했다 꺼내오는 클래스로 보이는데, 이 클래스에서 인스턴스를 넘기기 보다는 실제 메서드를 호출하는게 어떤지 궁금합니다.

2024-08-26 15:50 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/oauth2/provider/kakao/KakaoOAuth2ProviderService.java
> +    }
이 메서드는 매번 같은 값을 반환하는듯 한데 매번 만들어서 반환해야 할까요?

또한, 이 redirectUrl을 반환하는 책임과 아래의 getOauth2Member 메서드의 책임이 같이 묶이는 것으로 보인건지 궁금합니다. 서로 연관이 크게 없는 역할의 메서드들이 상속으로 인해 묶여있는듯 해서요!

2024-08-26 15:50 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/oauth2/provider/Oauth2ProviderComposite.java
> +}
추가로, 인스턴스를 get 하는 행위는 곧 다른 컴포넌트에서 주입받을 수 있는데 의존성 주입만을 위임한 클래스로 보여져서 약간 이상해 보였습니다. 인스턴스만 빼오는 클래스로 보여졌습니다.

2024-08-27 11:29 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/oauth2/provider/kakao/KakaoOAuth2ProviderService.java
> +    }
```getRedirectionLoginUrl()``` 이 메서드는 따로 빈을 등록해 반환하도록 수정했습니다!
두 번째로 redirectUrl과 getOauth2Member를 절차적인 연관이 존재한다고 생각했어요
현재 구현한 Oauth2 프로세스는 거의 모든 Oauth2 제공사의 로그인 페이지를 프론트에 리다이렉션 한 뒤에 인증코드를 받아 회원을 조회해야하는 절차적 연관이 존재하기 때문입니다.

2024-08-27 11:34 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/oauth2/provider/Oauth2ProviderComposite.java
> +}
> 추가로, 인스턴스를 get 하는 행위는 곧 다른 컴포넌트에서 주입받을 수 있는데 의존성 주입만을 위임한 클래스로 보여져서 약간 이상해 보였습니다. 인스턴스만 빼오는 클래스로 보여졌습니다.

인스턴스를 get하는 행위라는 말씀은 동의합니다. 그런데 다른 컴포넌트에서 주입받을 수 있다는 말씀은 조금 동의하기 어려운 부분인데, Oauth2ProviderService는 이 객체를 사용하는 쪽에서 곧바로 주입받기는 어렵다고 생각합니다. Kakao, Naver, Github처럼 여러 Provider가 존재하게되면 Oauth2ProviderService를 사용하는 Oauth2Service에서 직접 주입이 어렵다고 판단됩니다.

2024-08-27 11:37 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/group/service/S2GroupLocationService.java
> +        System.out.println("cellTokens = " + cellTokens);
네!

2024-08-27 11:49 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/oauth2/provider/Oauth2ProviderComposite.java
> +}
> 단순히 인스턴스들을 저장했다 꺼내오는 클래스로 보이는데, 이 클래스에서 인스턴스를 넘기기 보다는 실제 메서드를 호출하는게 어떤지 궁금합니다.

다른 컴포넌트에서 주입받기 어렵다면, 위 코멘트의 방식으로 수정하는 방향은 어떻게 생각하시나요?

2024-08-27 11:52 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/oauth2/provider/kakao/KakaoOAuth2ProviderService.java
> +    }
절차적인 연관만으로는 같은 클래스에 묶이는게 꼭 좋다 생각들지는 않습니다.
다만, Oauth2 기능 내에서의 절차적인 연관이 있기에 이 관점에서 연관은 있다 생각이 듭니다.
다시 보니 기준을 세우기 애매해 보이기도 합니다...

분리하셨으니, resolve 해두도록 하겠습니다.

2024-08-27 12:46 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/member/service/MemberService.java
> +    }
map + orElseGet을 유지하되 update 시 반환값은 없도록 수정했습니다

2024-08-27 12:46 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/member/domain/Member.java
> +        return this;
네 동의합니다.. 수정했습니다

2024-08-27 14:04 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/oauth2/provider/kakao/KakaoAuthorization.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
오! 그렇네요 설정했습니다

2024-08-27 14:58 UTC, merged