Feat/#3
AmorGakCo/Backend pull request #6
Opened 2024-07-17 01:40 UTC by songhaechan

## #️⃣연관된 이슈

> ex) #5 

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요.(이미지 첨부 가능)

## 💬리뷰 요구사항

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요.

2024-07-17 02:02 UTC, ohksj77 requested changes
Mapper는 추후 한가지 방법으로 합친다 하셨기에 리뷰하지 않았습니다.
redis 사용 부분의 인터페이스는 다른 기술로의 이전을 고려했다고 이해했습니다. 혹여나 다른 의도가 있다면 의견 나눠주시면 감사하겠습니다.

전반적으로 확장성이나 유지보수를 조금 더 신경쓰면 좋을 부분 위주로 코멘트를 남겨뒀습니다.

수고하셨습니다.

2024-07-17 02:09 UTC, ohksj77 requested changes
놓친 부분이 있어 추가합니다. 확인해주세요.

2024-07-17 02:09 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/location/controller/GroupLocationController.java
> +        return geoSpatialService.getNearByGroups(locationRequest);
GetMapping에 RequestBody를 사용하면 작동하나요?

2024-07-17 02:10 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/group/service/GroupService.java
> +        final Group group = groupMapper.toGroup(host, groupRegisterRequest, location, participants);
지금대로면 연관된 작업들을 한 번에 처리하지 않고 매번 만들어서 넣어줘야 하기에 약간 비효율적일 것 같습니다.

2024-07-17 06:58 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/group/controller/GroupController.java
> +    }
이런 규칙이 있었네요 수정했습니다

2024-07-17 07:33 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/group/service/GroupService.java
> +        final Group group = groupMapper.toGroup(host, groupRegisterRequest, location, participants);
아 이부분은 코드를 제거하지 않고 커밋을 했네요 host는 Participants에 포함되지않도록 설계를 변경했었습니다!

2024-07-17 07:37 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/group/repository/GroupRepository.java
> +    Optional<Group> findByIdWithMember(final Long groupId);
아 그렇네요 필드명도 host이니 host가 적절해보이네요

2024-07-17 07:45 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/group/dto/GroupRegisterResponse.java
> +public record GroupRegisterResponse(Long groupId) {}
CommonIdResponse라는 클래스를 global패키지에 만들어서 공통으로 사용하도록 했습니다

2024-07-17 08:28 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/group/service/GroupService.java
> +@Transactional
이 서비스가 전체적으로 읽기 위주인지 쓰기위주인지 판단하기에 일러서 일단 false로 걸어놨습니다. 쓰기가 많아지면 true를 전역으로 걸어둘 생각인데 괜찮을까요?

2024-07-17 08:34 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/group/service/GroupService.java
> +@Transactional
저는 잘못된 쓰기 트랜잭션 적용을 피하고 싶은 부분과 쓰기 트랜잭션들만 따로 명시하는게 읽기작업 외의 작업이 있다는걸 볼 수 있어서 선호하는데요, 이와 같이 해찬님 만의 기준을 이유가 명확하도록 세우셔서 하셨으면 좋겠다는 생각에 공유드립니다.

지금 이 부분도 그렇고 제 의견 중 큰 상관 없는 부분들은 본인만의 기준을 공유해주시면서 토론하면 더 좋을 것 같습니다.

2024-07-17 08:36 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/member/domain/Member.java
> +        this.gitHubUrl = "";
포인트는 null이 없다고 생각하고 작성했습니다. 그런데 DB입장에서 생각해보니 어떤 경우에 따라서 null로도 값을 받아와야할 수 있고 모든 엔티티에 일관성을 주기위해 Wrapper타입으로 변경하겠습니다.

2024-07-17 08:47 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/group/domain/Group.java
> +        this.endTime = endTime;
넵 예외적인 상황 처리가 아예 없었네요

2024-07-17 08:51 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/group/service/GroupService.java
> +@Transactional
잘못된 쓰기 트랜잭션 적용을 피하는 측면에서 공감합니다. 그런데 저는 반대로 읽기 트랜잭션을 메서드별로 걸어두는 것이 readOnly=true로 정확하게 명시해서 읽기 전용이라는 것을 잘 들어낸다 생각해서 읽기 트랜잭션을 따로 거는걸 선호합니다.
추가로 readOnly=true를 전역으로 걸었을 때 쓰기 트랜잭션에 잘못 걸린 경우 error가 발생하게되는데 이 부분도 피하고 싶었습니다. 물론 비효율적인 읽기가 발생하게 될 수도 있으나 아예 동작하지 않는 경우는 막을 수 있다고 생각합니다.

2024-07-17 08:59 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/group/service/GroupService.java
> +@Transactional
예외를 통해 알 수 있는 이슈가 나도 모르게 성능이 하락하거나 모르고 있는데 이슈가 있는 것보다 더 좋은 현상이라 생각합니다..! 
테스트만 적절히 해본다면 빠르게 걸러내고 수정할 수 있어서요!

혹시 이 부분에 대해 어떻게 생각하시나요?

2024-07-17 12:37 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/group/service/GroupService.java
> +                                () -> new ResourceNotFoundException(ErrorCode.GROUP_NOT_FOUND));
적용해보면서 조금 애매한 부분이 생겨서 논의가 필요할 것 같습니다!
```java
    public static JwtAuthenticationException accessTokenExpired() {
        throw new JwtAuthenticationException(ErrorCode.ACCESS_TOKEN_EXPIRED);
    }
```
위처럼 메서드 반환 타입을 예외 객체로 명시하게되면
<img width="820" alt="스크린샷 2024-07-17 오후 9 35 15" src="https://github.com/user-attachments/assets/bde3a3a9-317c-47e7-b5bc-2602c26cb651">
위처럼 throw하는 경우에 반환타입이 무의미해집니다.

반대로 
```java
    public static void accessTokenExpired() {
        throw new JwtAuthenticationException(ErrorCode.ACCESS_TOKEN_EXPIRED);
    }
```
반환타입을 void로 명시하게되면
람다식에서 예외로 인식하지 못해 컴파일에러가 발생합니다.

두 가지를 다 만족시킬 방법을 아직 찾지 못해서 일단은 JwtAuthenticationException해당 예외만 적용한 상태입니다.

2024-07-18 05:03 UTC, ohksj77 approved these changes
사소한 몇가지 코멘트 남겨놨습니다.

수고하셨습니다.

2024-07-18 05:03 UTC, ohksj77 commented on src/main/java/com/amorgakco/backend/geospatial/controller/GeospatialController.java
> +                new GeospatialRequest(width, height, latitude, longitude));
이 dto의 용도는 그저 데이터를 담았다가 바로 get으로 가져오는 것 같은데 ModelAttribute 어노테이션을 사용하거나 지금 이 dto 자체를 사용하지 않는건 고려하지 않으셨나요?

2024-07-18 05:39 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/member/domain/Member.java
> +        this.githubUrl = "";
null이어도 되네요 초기화하지 않겠습니다

2024-07-18 05:41 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/group/domain/ProgressStatus.java
> +public enum ProgressStatus {
다시 생각해보니 이 상태가 굳이 필요가 없다고 생각해서 제거했습니다.

2024-07-18 05:45 UTC, songhaechan commented on src/main/java/com/amorgakco/backend/geospatial/controller/GeospatialController.java
> +                new GeospatialRequest(width, height, latitude, longitude));
ModelAttribute는 RequestParam도 매핑하지만 Body까지  매핑하는걸로 알고있어서 제외했었고
굳이 DTO를 사용했던 이유는 getNearByGroups에 구체적인 파라미터 명시를 피하고 싶어서 dto로 래핑했습니다.
나중에 박스형태 조회가 아닌 원형 조회로 변경됐을 때 해당 인터페이스 자체를 변경해야하는데 인터페이스 변경은 피하고싶었습니다.

2024-07-18 08:13 UTC, merged