fix/#66
AmorGakCo/Backend pull request #67
Opened 2024-10-23 10:14 UTC by songhaechan

## #️⃣연관된 이슈

> ex) #66 

## 📝작업 내용

> 그룹 호스트인지에 따라서 프론트 UI가 변경돼야하기 때문에 서버 측에서 식별필드 추가
> 참여 요청을 보내고 아직 수락되지 않은 참여자를 식별하는 필드 추가
> 그룹 내역 조회에서 활성화그룹을 비활성화그룹으로 잘못 응답이 내려가는 중 (isBefore(), isAfter() 함수가 뒤바뀌어있음)
> GroupParticipation의 이름에 의미가 잘 드러나지 않아서 도메인 이름 변경 -> ParticipationRequest (그룹 참여 요청자들을 위한 도메인)
> 그룹 참여 제한 설정 (한 번에 5개 이상의 모각코 활동을 제한)

## 💬리뷰 요구사항

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요.

2024-10-28 00:32 UTC, ohksj77 requested changes
고생하셨습니다. 궁금한 점들 리뷰로 남겨두었으며, 리뷰 범위 외로도 코드를 보다 궁금해진 점들을 여기에 남겨봅니다.

1. Group이 boolean값을 반환하는 것까지가 아닌, 적합하지 않은 경우 예외를 던지는 로직까지 Group의 책임 아닐까요? 지금은 하나의 기능에 대한 책임이 여기저기에 퍼져있는 느낌입니다. 어떻게 생각하시는지 궁금합니다!
![스크린샷 2024-10-28 오전 9 26 34](https://github.com/user-attachments/assets/09537b87-a73a-4e2c-9922-e24dfafbefaf)

2. group-locations 가 이 컨트롤러가 다루는 자원으로 보이는데, groups가 컨트롤러의 공통 경로인 이유가 궁금합니다! groups가 공통 경로인 다른 컨트롤러도 존재하는 것으로 보여서요!
![스크린샷 2024-10-28 오전 9 28 54](https://github.com/user-attachments/assets/659093a3-26f3-4f16-b934-56b02e0e5789)

2024-10-28 00:32 UTC, ohksj77 commented on main/src/main/java/com/amorgakco/backend/group/controller/GroupController.java
>      }
추가로, 200 상태 코드의 경우 ResponseStatus를 명시하지 않았다고 이해하면 될까요?

2024-10-28 00:32 UTC, ohksj77 commented on main/src/main/java/com/amorgakco/backend/participationrequest/domain/ParticipationRequest.java
> +public class ParticipationRequest extends BaseTime {
기존에 사용하던 DTO 네이밍과 혼동이 생길 수 있을 것 같습니다. 다른 이름으로 수정해보는건 어떤가요?

2024-10-28 00:32 UTC, ohksj77 commented on main/src/main/java/com/amorgakco/backend/participationrequest/service/ParticipationRequestValidator.java
> +        group.validateParticipation(new Participant(member));
group.validateParticipation() 메서드 내부를 보니, Participant가 포함되었는지만 판단하는 것으로 보이는데, 여기서 new Participant를 하기 보다는 group에 participant를 추가할 때 이러한 검증을 수행한 뒤 적합하면 추가하는 것은 어떤가요?

2024-10-28 00:32 UTC, ohksj77 commented on main/src/main/java/com/amorgakco/backend/participationrequest/service/ParticipationRequestValidator.java
> +        }
저장된 participant의 수가 6명부터는 무조건 예외를 던지는게 옳을까요? 예외 상황까지는 아니라고 보여져서 여쭈어봅니다. 6명이 저장되는 순간 부터는 무조건 이 로직에서는 예외가 발생할 것 같아서요!

2024-10-28 00:37 UTC, ohksj77 commented on main/src/main/java/com/amorgakco/backend/participationrequest/service/ParticipationRequestValidator.java
> +        }
혹은 이미 추가할 수 없는 상태라는 것을 알려주는 API가 존재하는 것일까요?

2024-10-28 07:17 UTC, songhaechan commented on main/src/main/java/com/amorgakco/backend/participationrequest/domain/ParticipationRequest.java
> +public class ParticipationRequest extends BaseTime {
네... Request를 DTO에서 사용중이라 혼란이 있을 것 같다고 생각이 저도 들긴하는데
해당 도메인은 그룹장의 참여 승인을 기다리는 대기열 느낌이 있어서
ParticipationQueue도 고려해봤는데 네이밍이 자료구조스럽긴한데 어떨까요?

2024-10-28 13:13 UTC, songhaechan commented on main/src/main/java/com/amorgakco/backend/global/exception/IllegalAccessException.java
> +    }
IllegalAccessException 자체가 자바 기본 예외라 저도 신경쓰이고 있었는데
이참에 다 찢어놨습니다!

2024-10-28 13:13 UTC, songhaechan commented on main/src/main/java/com/amorgakco/backend/group/controller/GroupController.java
>      }
> 추가로, 200 상태 코드의 경우 ResponseStatus를 명시하지 않았다고 이해하면 될까요?
넵 맞습니다

2024-10-28 13:18 UTC, songhaechan commented on main/src/main/java/com/amorgakco/backend/group/controller/GroupController.java
>      }
> rest api 설계 시 id는 자원 바로 다음 경로에 넣는 것은 어떤가요? [레퍼런스](https://until.blog/@thingk0/%EB%82%B4%EA%B0%80-%EC%93%B0%EB%A0%A4%EA%B3%A0-%EB%A7%8C%EB%93%A0-restfulapi-%EC%84%A4%EA%B3%84-%EA%B7%9C%EC%B9%99--) 다음 api path는 이렇게 수정할 수 있습니다.
> 
> ```
> /groups/basic/{groupId} -> /groups/{groupId}/basic
> ```
> 
> 또한, basic 이나 detail과 같은 표현은 필요한 api에만 사용해도 될 것 같으며, 가능하다면 더 구체적인 단어를 고민해봐도 좋습니다.

으악 이건 왜 이렇게 했는지 이해가 안되네요 수정했습니다 ㅋㅋ

2024-10-28 14:52 UTC, songhaechan commented on main/src/main/java/com/amorgakco/backend/participationrequest/service/ParticipationRequestValidator.java
> +        }
> 저장된 participant의 수가 6명부터는 무조건 예외를 던지는게 옳을까요? 예외 상황까지는 아니라고 보여져서 여쭈어봅니다. 6명이 저장되는 순간 부터는 이 로직에서는 무조건 예외가 발생할 것 같아서요!

음 이 로직이 애매하게 해석될 여지가 있어보이네요.
본래 의도는 그룹에 저장된 participant가 아니라 한 멤버가 참여중인 그룹의 수를 5개 이하로 제한하려는 의도입니다.

2024-10-29 02:15 UTC, ohksj77 commented on main/src/main/java/com/amorgakco/backend/participationrequest/service/ParticipationRequestValidator.java
> +        }
설명 감사합니다. 이해했습니다.

2024-10-29 02:16 UTC, ohksj77 approved these changes
고생하셨습니다.

2024-10-29 04:05 UTC, merged